@component('mail::message')
# Hi {{ $data['name'] }}

An enquiry is generated by <b>{{ $data['email'] }}</b> who is conveying the following message.
<hr>
{{ $data['message'] }}
<hr><br>

Thanks,<br>
{{ config('app.name') }}
@endcomponent
